In [1]:
import numpy as np

### 25 Questions of numpy

Part A: Basic Array Manipulation (Q1–Q10)

1. Create a NumPy array of 10 zeros

In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Create a NumPy array of 10 ones

In [4]:
o = np.ones(10)
print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3. Create an array of integers from 10 to 49

In [5]:
i = np.arange(10,50)
print(i)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Reverse the array



In [6]:
a = np.array([7,6,5,4,3,2,1])
print(a[::-1])

[1 2 3 4 5 6 7]


5. Reshape an array of 9 elements into 3x3



In [7]:
re = np.arange(9)
print(re)
re = re.reshape(3,3)
print(re)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


6. Create a 3x3 identity matrix

In [9]:
iden = np.full((3,3),'i')
print(iden)

[['i' 'i' 'i']
 ['i' 'i' 'i']
 ['i' 'i' 'i']]


7. Create an array of 10 random integers from 0–100

In [11]:
ran = np.random.randint(0,100, size=10)
print(ran)

[74 86 59  8 52 42 51 23 37 52]


8. Find the maximum, minimum, mean of that array

In [12]:
arr = np.array([1,2,4,4,6,5,7,9])
print("Max is :", np.max(arr))
print("Min is :", np.min(arr))
print("Mean is :", np.mean(arr))

Max is : 9
Min is : 1
Mean is : 4.75


9. Replace all odd numbers with -1

In [18]:
arr = np.array([1,2,4,4,6,5,7,9]) #fancy indexong and slicing
arr[arr % 2 == 1] = -1
print(arr)

[-1  2  4  4  6 -1 -1 -1]


10. Multiply all elements by 3 and print new array

In [13]:
mu = np.array([1,2,3])
three = mu * 3
print(three)

[3 6 9]


11. Create a 1D array from 0–15 and reshape it into 4x4

In [25]:
oned = np.arange(16)
oned = (oned.reshape(4,4))
print(oned)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


12. Extract the 2nd row

In [27]:
second_row = oned[1:2]
print(second_row)

[[4 5 6 7]]


13. Extract the last column

In [30]:
last_col = oned[:,3:]
print(last_col)

[[ 3]
 [ 7]
 [11]
 [15]]


14. Slice the middle 2x2 block

In [32]:
middle = oned[1:3,1:3]
print(middle)

[[ 5  6]
 [ 9 10]]



15. Filter all values greater than 7

In [33]:
greater_than_7 = oned[oned>7]
print(greater_than_7)

[ 8  9 10 11 12 13 14 15]



16. Set all values > 10 to 10

In [37]:
oned[oned>10] = 10
print(oned)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 10]
 [10 10 10 10]]


17. Use boolean mask to set even numbers to 0

In [42]:
oned[oned % 2 == 0] = 0
print(oned)

[[0 1 0 3]
 [0 5 0 7]
 [0 9 0 0]
 [0 0 0 0]]


18. Fancy index: select elements at indices [1, 3, 5, 7]

In [56]:
harsh = np.array([10,20,1,4,6,0,5,8+6,0,0])
ind = harsh[[1,3,5,7]]
print(ind)

[20  4  0 14]


19. Create a 3x3 array and add 5 to every element

In [58]:
elem = np.full((3,3), 69)
print(elem + 5)

[[74 74 74]
 [74 74 74]
 [74 74 74]]


In [67]:
norm = (harsh-harsh.mean())/harsh.std()
print(norm)
print(norm.mean())
print(norm.std())

[ 0.62166987  2.17584455 -0.77708734 -0.31083494  0.         -0.93250481
 -0.15541747  1.24333974 -0.93250481 -0.93250481]
-2.2204460492503132e-17
1.0


21. Create a 5x5 array of random integers (0–100)

In [75]:
myarr = np.random.randint(0,100, 25)
myarr = (myarr.reshape(5,5))
print(myarr)

[[91 74 64 92 35]
 [89 89 67 18 86]
 [ 9 67 91 72 50]
 [40 60 91 40  5]
 [28 28 10 57 96]]


22. Find the row-wise and column-wise mean

In [ ]:
row_mean = myarr.mean(axis=1) #if you want to iterrate means use axis
print(row_mean)
col = myarr.mean(axis=0)
print(col)

[71.2 69.8 57.8 47.2 43.8]
[51.4 63.6 64.6 55.8 54.4]


23. Replace values < 50 with 0

In [88]:

myarr[myarr < 50] = 0
print(myarr)

[[91 74 64 92  0]
 [89 89 67  0 86]
 [ 0 67 91 72 50]
 [ 0 60 91  0  0]
 [ 0  0  0 57 96]]


24. Flatten it, then reshape back to 5x5

In [92]:
print(myarr.flatten())
print(myarr.reshape(5,5))


[91 74 64 92  0 89 89 67  0 86  0 67 91 72 50  0 60 91  0  0  0  0  0 57
 96]
[[91 74 64 92  0]
 [89 89 67  0 86]
 [ 0 67 91 72 50]
 [ 0 60 91  0  0]
 [ 0  0  0 57 96]]


25. Generate 1D array of 100 random numbers and find:<br>

Mean

Standard deviation

Count how many are > mean



In [102]:
arr100 = np.random.randint(101,size=20)
print(arr100.mean())
print(arr100.std())
arr100[arr100>arr100.mean()] = 1
print(np.count_nonzero(arr100==1))

47.25
33.73407031474263
10
