### Numpy Mastery

In [2]:
import numpy as np

### 1. Array Creation

##### all the important ways to create an array 👇

In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.arange(1,10)
c = np.linspace(1,50,20) #1 se 50 ke bich mai 20 element
d = np.zeros((3,4))
e = np.ones((1,2))
f = np.full((3,2),8)

#### 2. Shape, Reshape, Flatten

In [15]:
arr = np.arange(12)
arr.shape

(12,)

In [20]:
arr = arr.reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 3. Maths Ops

In [27]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x+y)
print(x*y)
print(np.sqrt(y))
print(np.mean(y))

[5 7 9]
[ 4 10 18]
[2.         2.23606798 2.44948974]
5.0


#### 4. Indexing & Slicing

In [34]:
i = np.arange(10)
print(i[0])
print(i[2:5])
print(i[::-1])

0
[2 3 4]
[9 8 7 6 5 4 3 2 1 0]


In [41]:
n = np.array([[1, 2], [3, 4]])
print(n)
print(n[0,1])
print(n[:,1:])

[[1 2]
 [3 4]]
2
[[2]
 [4]]


#### 5. Boolean & Fancy Indexing

In [47]:
ar = np.array([1, 4, 6, 8, 10])
print(ar[ar>5])
print(ar[[0,2,4]])

[ 6  8 10]
[ 1  6 10]


#### 6. Broadcasting

In [48]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print(a + b)  # row-wise
print(a + 5)  # scalar #streches


[[11 22 33]
 [14 25 36]]
[[ 6  7  8]
 [ 9 10 11]]


#### 7. Random

In [51]:
np.random.rand(4) #0 aur 1 ke bich mai saara counts nikal ke dega
np.random.rand(50)

array([0.4312057 , 0.98579455, 0.85762548, 0.60776267, 0.23877753,
       0.93560987, 0.51197144, 0.76164972, 0.95975878, 0.48993465,
       0.64985575, 0.16120953, 0.81185918, 0.42924254, 0.41491811,
       0.64791507, 0.502337  , 0.8792618 , 0.40371655, 0.05593663,
       0.21931101, 0.24262105, 0.16835608, 0.06075505, 0.40975143,
       0.93624374, 0.75674744, 0.39565373, 0.96098364, 0.30726987,
       0.75751522, 0.81683031, 0.93716578, 0.18669206, 0.61116034,
       0.19822691, 0.40738323, 0.85085512, 0.61243048, 0.06766786,
       0.02579008, 0.734912  , 0.83178183, 0.91430764, 0.92502193,
       0.33038545, 0.61664549, 0.73133931, 0.53616363, 0.69938368])

In [56]:
np.random.randn(5)
np.random.randn(2,2) #(-2,2) tk ka range hai

array([[-1.05104992, -1.52908447],
       [ 0.0473933 ,  1.83478709]])

In [62]:
print(np.random.randint(1,5, size=5)) #prints grpm x to y and soze=no of elems

[1 4 3 4 3]


In [64]:
print(np.random.randint(1, 100, (2, 3)))

[[32 40 39]
 [37 53 56]]
