## Numpy array operations

In [1]:
import numpy as np


In [5]:
arr = np.arange(0,11)
print("Basic Slicling", arr[2:7])
print("Basic Slicling with step", arr[2:8:2])
print("Negative Slicing", arr[-2])

Basic Slicling [2 3 4 5 6]
Basic Slicling with step [2 4 6]
Negative Slicing 9


In [8]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific Element", arr_2d[1,2]) #1st row ka 2nd element with index start with 0
print("Entire row : ", arr_2d[1])
print("Entire column : ", arr_2d[:,0])

Specific Element 6
Entire row :  [4 5 6]
Entire column :  [1 4 7]


### Sorting in arrays

In [13]:
unsorted = np.array([1,3,5,7,9,2,4,6])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by coloum ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row ", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [1 2 3 4 5 6 7 9]
Sorted 2D array by coloum  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row  [[1 3]
 [1 2]
 [2 3]]


### Filter

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print(even_number)

[ 2  4  6  8 10]


### Filter with mask

In [15]:
mask = numbers > 5
print("Numbers > 5 are :", numbers[mask])

Numbers > 5 are : [ 6  7  8  9 10]


### Fancy Indexing vs np.where

In [19]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)
print("WHERE", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
WHERE [ 6  7  8  9 10]


In [21]:
condition_array = np.where(numbers>5, numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing data

In [23]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


#### Array Compatibility

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compalitibility Shapes", a.shape == b.shape)

Compalitibility Shapes False


##### For additing row 

In [ ]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row)) #vstack hamesha hi row add krta hai
print(original)
print(with_new_row)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


##### For additing coloum

In [28]:
new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(original)
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


#### Deleting

In [31]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("Array after deletion ", deleted)

Array after deletion  [1 2 4 5]
