## Numpy

#### Phase 1

In [2]:
import numpy as np

### Creating array from list

In [3]:
arr_1d = np.array([1,2,3,4]) #it takes only one argument as list
print(arr_1d)
arr_2d = np.array([[1,2],
                   [3,4]])
print(arr_2d)

[1 2 3 4]
[[1 2]
 [3 4]]


### Numpy vs Array

In [17]:

py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


### Creating Arrays from strach

In [16]:

zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.79611151 0.04885541 0.05515998]
 [0.50037273 0.5089381  0.83800858]]
sequnce array: 
 [ 0  2  4  6  8 10]


### Vector, Matrices and Tensor

In [4]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrice = np.array([[1,2,3],
                    [4,5,6]])
print("Matrice: ", matrice)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]]) #multi dimension array
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrice:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [5]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DataType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DataType  int64


### Array Reshaping

In [15]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array " , reshaped)

flattend = reshaped.flatten()
print("Flattend array " , flattend)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Ravel array " , raveled)

# Transpose
transpose = reshaped.T
print("Transposed array " , transpose)



Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattend array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
